spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wansenerp?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    dynamic:
      druid:
        max-wait: 60000
        initial-size: 5
        min-idle: 5
        max-active: 20
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 20
          max-wait: 100
          max-idle: 20
          min-idle: 5
      timeout: 10000
